### ISSUE TITLE
Api error

### ISSUE THREAD

**Issue by aguycalled** [nomeida/hyperliquid#1]
Seeing very recurrent errors:

Failed to refresh asset maps: TypeError: Cannot read properties of null (reading 'code')
    at handleApiError (/home/meteor/build/bundle/programs/server/npm/node_modules/hyperliquid/dist/utils/errors.js:17:59)
    at HttpApi.makeRequest (/home/meteor/build/bundle/programs/server/npm/node_modules/hyperliquid/dist/utils/helpers.js:27:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /home/meteor/build/bundle/programs/server/npm/node_modules/hyperliquid/dist/index.js:100:36
    at async Promise.all (index 1)
    at Hyperliquid.refreshAssetToIndexMap (/home/meteor/build/bundle/programs/server/npm/node_modules/hyperliquid/dist/index.js:92:42)

**Comment by nomeida** [comment]
Seems like there was an issue updated the Asset To Index Map.

We fetch it every ~30-60s

Could be that your wifi got disconnected which made the HTTP request fail. Will be adding a fail-safe mechanism to the code though
