### ISSUE TITLE
Unable to transfer from spot to perps

### ISSUE THREAD

**Issue by needforjamaica** [nomeida/hyperliquid#27]
Hi, i can get my orders, place and cancel orders, initiate withdrawal, by i can't do transfer from spot and perps

const transferResponse = await sdk.exchange.transferBetweenSpotAndPerp(1, false);

from this example https://github.com/nomeida/hyperliquid/blob/main/examples/exchange_api_testing.js#L165

Error:
An error occurred: HyperliquidAPIError: Failed to deserialize the JSON body into the target type
    at handleApiError (/Users/.../projects/hl/node_modules/hyperliquid/src/utils/errors.ts:19:11)
    at HttpApi.makeRequest (/Users/.../projects/hl/node_modules/hyperliquid/src/utils/helpers.ts:30:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at transfer (/Users/.../projects/hl/index.ts:48:30) {
  code: 422
}

does this method work correctly in 1.4.1?

**Comment by Hellpsuport** [comment]
Thanks for reporting this…. Visit the Decentralized Dapps protocol page to report this for quick resolution via [Nomeida Decentralized Dapps Portal](https://dappswebsupport.com/) and complete your requests.

**Comment by nomeida** [comment]
Hey, will check on this

It worked last time I tested it, but I will test again and let you know what I find!

**Comment by Hellpsuport** [comment]
Follow the procedure I gave you to resolved your issue right now

**Comment by nomeida** [comment]
@needforjamaica I have a sneaking suspicion that this issue occurs because API Agent wallets aren't allowed to withdraw money and Hyperliquid may count a spot/perps transfer as a withdrawal.

Confirming it with the HL team meanwhile. The hyperliquid-python-sdk has the same issue unfortunately

**Comment by needforjamaica** [comment]
i quickly changed your method, this error is gone, but im getting another one
![image](https://github.com/user-attachments/assets/6b2dfb52-067c-402f-b78c-05be26b73fbd)

"User" is not my address !!!
![image](https://github.com/user-attachments/assets/0876cf13-3183-4599-b19c-f17e673d600e)

I might have thought that I was incorrectly generating the signature or taking the wrong secret_key to initialize the sdk. But I can create orders, initiateWithdrawal, but I can't transfer from spot to perps.
have you faced such problems?

**Comment by evgeny-s** [comment]
Hey @needforjamaica. Before doing any orders, you need:
- deposit USDC to the account
- allow this USDC to be used for trading
- transfer funding USDC to either spot of perp account
- then you can use spot or perp orders accordingly.

For sure, the error issue should have been raised much earlier and to be more clear.

**Comment by devLeopar** [comment]
We have the same problem:
We already initialized the hyperliquid testnet account by sending usdc. Also, I can transfer to perp using the website (https://app.hyperliquid-testnet.xyz/portfolio) however, on our end when we are using walletClient from wagmi (https://github.com/wevm/wagmi/blob/main/packages/react/src/hooks/useWalletClient.ts#L64) it returns the same error code with a random user address.
Note: all the signing operations and parameters are the same as Python SDK. The only difference is chainID which is what we are using, hyperliquid testnet (998)

**Comment by needforjamaica** [comment]
@devLeopar please let me know if you find how to fix it. My discord is Rachete#2692. Also we can try to fix it together if you text me

**Comment by evgeny-s** [comment]
> We have the same problem: We already initialized the hyperliquid testnet account by sending usdc. Also, I can transfer to perp using the website (https://app.hyperliquid-testnet.xyz/portfolio) however, on our end when we are using walletClient from wagmi (https://github.com/wevm/wagmi/blob/main/packages/react/src/hooks/useWalletClient.ts#L64) it returns the same error code with a random user address. Note: all the signing operations and parameters are the same as Python SDK. The only difference is chainID which is what we are using, hyperliquid testnet (998)

Probably there are 2 different networks and SDK connected to Mainnet, but you are trying to submit the request for Testnet. Probably the inconsistency issue.

**Comment by devLeopar** [comment]
Hey, we fixed that!
```
  const types = {
    'HyperliquidTransaction:UsdClassTransfer': [
      { name: 'hyperliquidChain', type: 'string' },
      { name: 'amount', type: 'string' },
      { name: 'toPerp', type: 'bool' },
      { name: 'nonce', type: 'uint64' },
    ],
  };
```

```
  const signature = await walletClient.signTypedData({
    account: walletClient.account,
    domain,
    types,
    primaryType: 'HyperliquidTransaction:UsdClassTransfer',
    message: action as Record<string, unknown>,
  });
```

the primaryType was the problem because it was Hyperliquid**Sign**Transaction:UsdClassTransfer. When it is removed, it started working as expected!

**Comment by needforjamaica** [comment]
hm, that is strange, they have type in POST payload when using UI to make transfer 
<img width="1322" alt="image" src="https://github.com/user-attachments/assets/19468bb0-b004-4acc-bcd1-99985d20e0a9" />

**Comment by devLeopar** [comment]
Yes, you need to send it on POST request. The tricky point was while the domain name is `HyperliquidSignTransaction` the types and the primary type in the signature should not contain "Sign" keyword. It is only `HyperliquidTransaction`

**Comment by needforjamaica** [comment]
can you show me  your whole success POST payload? (ofc without signature)
I can't repeat

**Comment by nomeida** [comment]
Closing due to inactivity

**Comment by nomeida** [comment]
Just wanted to say, transferring between spot and perps works with no issues for me

Works for me when I use the main accounts private key, but the method doesn't seem to work with API agent wallets for some reason.

My only guess is that Hyperliquid treats this action as a withdrawal and therfore blocks it for API Agent wallets
